name: Test Container - Gotenberg

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'
    paths:
      - 'gotenberg/**'
  pull_request:
    branches: 
      - 'main'
    paths: 
      - 'gotenberg/**'

jobs:
    test-container:
      name: 'Test Container'
      uses: raschmitt/dev-containers/.github/workflows/test-container-workflow.yml@feat/upgrade-docker-compose
      with:
        container-name: gotenberg
