name: Test Container - SqlServer2022

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'
    paths:
      - 'sql-server/2022/**' 
  pull_request:
    branches: 
      - 'main'
    paths: 
      - 'sql-server/2022/**'

jobs:
    test-container:
      name: 'Test Container'
      uses: raschmitt/dev-containers/.github/workflows/test-container-workflow.yml@main
      with:
        container-name: sql-server
        subfolder: 2022