on:
  workflow_call:
    inputs:
      container-name:
        required: true
        type: string
      subfolder:
        required: false
        type: string
      os: # only used for sql-server-2017, while this is not fixed: https://github.com/microsoft/mssql-docker/issues/881
        required: false
        type: string
        default: 'ubuntu-latest'  

jobs:
  test-container-workflow:
    runs-on: ${{ inputs.os }}
    environment: production
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
    
      - name: 'Build container'
        run: |
          if [ -n "${{ inputs.subfolder }}" ]; then
            docker compose -f ${{ inputs.container-name }}/${{ inputs.subfolder }}/docker-compose.yml up -d
          else
            docker compose -f ${{ inputs.container-name }}/docker-compose.yml up -d
          fi
      
      - name: 'Wait until container is healthy'
        uses: raschmitt/wait-for-healthy-container@v1
        with:
          container-name: ${{ inputs.container-name }}
