on:
  workflow_call:
    inputs:
      container-name:
        required: true
        type: string
      subfolder:
        required: false
        type: string

jobs:
  test-container-workflow:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
    
      - name: 'Build container'
        run: |
          if [ -n "${{ inputs.subfolder }}" ]; then
            docker compose -f ${{ inputs.container-name }}/${{ inputs.subfolder }}/docker-compose.yml up -d
          else
            docker compose -f ${{ inputs.container-name }}/docker-compose.yml up -d
          fi

          sleep 30 
          
          docker ps -a

          sleep 30

          docker ps -a
      
      - name: 'Wait until container is healthy'
        uses: raschmitt/wait-for-healthy-container@v1
        with:
          container-name: ${{ inputs.container-name }}
